# Sentiment Analysis & Word Vectors

Import Libarires

In [4]:
import numpy as np
import pandas as pd
import spacy
import en_core_web_lg
nlp = en_core_web_lg.load()

### Word Vectors 

Below we use some examples for Word 2 vec to capture  words as vectors that captures their meaning and semantic similarity and relationship. A

In [9]:
# Access the vector represenatation of sentences and words
nlp(u'lion').vector

array([  1.2746  ,   0.46242 ,  -1.1829  ,  -5.2661  ,  -2.7128  ,
         1.8521  ,  -0.94273 ,   2.1865  ,   6.503   ,   0.6704  ,
         1.5361  ,   2.5992  ,  -0.36233 ,   4.3965  ,  -6.5644  ,
         1.6141  ,  -1.2897  ,   2.1184  ,  -0.63654 ,  -3.4572  ,
        -4.3771  ,   4.2074  ,  -3.6411  ,  -0.97214 ,   1.3253  ,
        -2.3125  ,  -3.6531  ,  -2.8398  ,   2.7913  ,  -1.53    ,
        -2.9984  ,  -2.6357  ,   0.50615 ,  -2.6925  ,   4.3401  ,
        -5.6017  ,   0.045691,   4.3832  ,  -0.19535 ,  -1.0751  ,
         0.32172 ,   2.4395  ,   4.6638  ,   3.4471  ,  -3.3847  ,
        -1.8238  ,   0.70212 ,   0.58557 ,   5.0032  ,  -3.1072  ,
         1.2364  ,   7.4595  ,   0.057368,   1.0111  ,  -1.0827  ,
         0.69113 ,   2.8009  ,  -3.4383  ,  -1.0599  ,  -2.2627  ,
        -5.149   ,  -5.0636  ,   3.1405  ,   1.0793  ,  -0.72892 ,
        -3.9939  ,  -0.69551 ,  -0.55767 ,   3.2555  ,  -2.9449  ,
         4.7114  ,   1.6388  ,   1.3828  ,   1.4255  ,  -3.233

In [11]:
nlp(u'I know that for several reasons Natural Language Processing can be a hard topic to cover').vector

array([-1.3447682 ,  2.257493  , -3.0360641 , -0.58615243,  0.50969756,
        0.7050806 ,  1.3814132 ,  4.2003093 , -2.5791993 ,  0.9548561 ,
        7.5432315 ,  1.8662556 , -4.9119344 ,  0.3565063 ,  1.6630428 ,
        0.6511826 ,  3.0648608 , -2.6400926 , -3.4817035 , -1.7936326 ,
        0.9469031 , -0.4082913 , -1.782362  , -1.6423051 , -0.52906626,
       -2.6012905 , -2.5822732 , -0.4071854 , -2.4858875 ,  0.7437282 ,
        2.2198625 , -1.1783706 , -1.6373781 ,  0.16664371, -0.27323   ,
       -0.8290928 ,  0.5215054 ,  0.83901346,  3.4933631 ,  0.3876384 ,
        0.8264105 ,  0.93310225,  0.38192904, -0.36310306, -1.8834537 ,
        2.5086365 ,  2.87784   , -4.4239097 , -1.1763743 ,  1.4912817 ,
       -0.24169624,  0.39435187, -0.05197951, -6.23575   , -3.5920532 ,
        0.887545  , -0.3185535 ,  1.6171355 ,  1.7095331 ,  0.56552684,
        3.0037236 , -0.1760025 , -0.51229024,  0.28779125,  1.2488239 ,
        1.367302  , -2.5299964 , -4.0484076 ,  0.9164686 ,  3.05

In [13]:
#gettinf the shape
nlp(u'I know that for several reasons Natural Language Processing can be a hard topic to cover').vector.shape

(300,)

using tokens to find similarity between words

In [15]:
tokens = nlp(u'lion cat pet')

In [17]:
#checking for similarity between the tokens set up usining cosine similarity
for token1 in tokens:
    for token2 in tokens:
        print(token1.text, token2.text, token1.similarity(token2))

lion lion 1.0
lion cat 0.3854507803916931
lion pet 0.20031583309173584
cat lion 0.3854507803916931
cat cat 1.0
cat pet 0.732966423034668
pet lion 0.20031583309173584
pet cat 0.732966423034668
pet pet 1.0


In [19]:
tokens = nlp(u'like love hate')

In [21]:
#checking for similarity between the tokens set up usining cosine similarity
for token1 in tokens:
    for token2 in tokens:
        print(token1.text, token2.text, token1.similarity(token2))

like like 1.0
like love 0.521263837814331
like hate 0.5065141320228577
love like 0.521263837814331
love love 1.0
love hate 0.5708349943161011
hate like 0.5065141320228577
hate love 0.5708349943161011
hate hate 1.0


In [25]:
#checking for vocabularey vectors
nlp.vocab.vectors.shape

(514157, 300)

In [42]:
#getting a new token
tokens = nlp(u'dog cat nargle')

In [44]:
for token in tokens:
    print(token.text, token.has_vector, token.vector_norm, token.is_oov)

dog True 75.254234 False
cat True 63.188496 False
nargle False 0.0 True


### Vector Arithmetic

In [47]:
from scipy import spatial
cosine_similarity = lambda vec1, vec2: 1 - spatial.distance.cosine(vec1, vec2)

In [49]:
king = nlp.vocab['king'].vector
man =  nlp.vocab['man'].vector 
woman =  nlp.vocab['woman'].vector 

In [51]:
#king - man + won = new_vector similar to queen, princess
new_vector = king - man + woman
computed_similarities = []
for word in nlp.vocab:
    if word.has_vector:
        if word.is_lower:
            if word.is_alpha:
                similarity = cosine_similarity(new_vector, word.vector)
                computed_similarities.append((word, similarity))
        

In [53]:
computed_similarities = sorted(computed_similarities, key= lambda item: - item[1])

In [59]:
print([t[0].text for t in computed_similarities[:100]])

['king', 'and', 'that', 'several', 'where', 'she', 'they', 'woman', 'there', 'should', 'these', 'would', 'those', 'to', 'cause', 'ought', 'who', 'reasons', 'might', 'not', 'this', 'when', 'could', 'somethin', 'were', 'all', 'a', 'have', 'he', 'for', 'must', 'lion', 'love', 'space', 'what', 'may', 'it', 'was', 'cover', 'topic', 'you', 'like', 'or', 'be', 'had', 'are', 'nothin', 'has', 'need', 'can', 'is', 'how', 'b', 'know', 'does', 're', 'hard', 'p', 'havin', 'on', 'why', 'man', 'did', 's', 'c', 'pet', 'we', 'j', 'z', 'cart', 'g', 'd', 'cat', 'dog', 'h', 'n', 'l', 'x', 'sha', 'k', 'e', 'y', 'r', 'hate', 'dare', 'pm', 'm', 'f', 'lovin', 'ü', 'ö', 'w', 'bout', 'q', 'i', 'ä', 'am', 'co', 'll', 'let']


# Vader Sentiment Analysis 

VADER also know as (Valence Aware Dictionary for Sentiment Reasoning) is a model used for text sentiment analysis that is sensitive to both polarity, that is whether something is positive or negative,
and intensity, that is the strength of the emotion. It is  available in the NLTK package and can be applied directly to unlabeled text data. VADER sentiment analysis
relies on a dictionary which maps lexical features to emotion intensities, called sentiment scores.The sentiment score of a text can then be attained
by summing up the intensity of each word in the text.

In [65]:
import nltk
# g3t the vader lexicon dictionary
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\Owner\AppData\Roaming\nltk_data...


True

In [67]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer

In [69]:
sid = SentimentIntensityAnalyzer()

In [71]:
a = 'This was a good movie.'
sid.polarity_scores(a)

{'neg': 0.0, 'neu': 0.508, 'pos': 0.492, 'compound': 0.4404}

In [73]:
a = "This was the best, most awesome movie EVER MADE!!!"
sid.polarity_scores(a)

{'neg': 0.0, 'neu': 0.425, 'pos': 0.575, 'compound': 0.8877}

In [75]:
a = "This was the WORST movie that has ever disgraced the screen"
sid.polarity_scores(a)

{'neg': 0.465, 'neu': 0.535, 'pos': 0.0, 'compound': -0.8331}

### Sample Amazon Text Sentiment Analysis

In [78]:
df = pd.read_csv(r"C:\Users\Owner\Desktop\UPDATED_NLP_COURSE\UPDATED_NLP_COURSE\04-Semantics-and-Sentiment-Analysis\amazonreviews.tsv", sep='\t')
df.head()

label                                             review
0   pos  Stuning even for the non-gamer: This sound tra...
1   pos  The best soundtrack ever to anything.: I'm rea...
2   pos  Amazing!: This soundtrack is my favorite music...
3   pos  Excellent Soundtrack: I truly like this soundt...
4   pos  Remember, Pull Your Jaw Off The Floor After He...

In [82]:
#get basic stats of the dataset
df.describe().transpose()

count unique                                                top  freq
label   10000      2                                                neg  5097
review  10000  10000  Stuning even for the non-gamer: This sound tra...     1

In [84]:
# check for unique values in the label column
df['label'].value_counts()

label
neg    5097
pos    4903
Name: count, dtype: int64

In [90]:
#check for null values
df.isnull().sum()

label     0
review    0
dtype: int64

In [92]:
# in case of null values drop nulls from data set
df.dropna(inplace= True)

In [100]:
blanks= []
for i, lb, rv in df.itertuples():
    if type(rv) == str:
        if rv.isspace():
            blanks.append(i)

In [104]:
# drop any blanks if any review texts are balck
df.drop(blanks, inplace=True)

In [106]:
#check the first review
df.iloc[0]['review']

'Stuning even for the non-gamer: This sound track was beautiful! It paints the senery in your mind so well I would recomend it even to people who hate vid. game music! I have played the game Chrono Cross but out of all of the games I have ever played it has the best music! It backs away from crude keyboarding and takes a fresher step with grate guitars and soulful orchestras. It would impress anyone who cares to listen! ^_^'

In [108]:
# check the polarity score for the above review and how vader classify it
sid.polarity_scores(df.iloc[0]['review'])

{'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'compound': 0.9454}

In [110]:
df['scores'] = df['review'].apply(lambda review: sid.polarity_scores(review))

In [112]:
df.head()

label                                             review  \
0   pos  Stuning even for the non-gamer: This sound tra...   
1   pos  The best soundtrack ever to anything.: I'm rea...   
2   pos  Amazing!: This soundtrack is my favorite music...   
3   pos  Excellent Soundtrack: I truly like this soundt...   
4   pos  Remember, Pull Your Jaw Off The Floor After He...   

                                              scores  
0  {'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'co...  
1  {'neg': 0.018, 'neu': 0.837, 'pos': 0.145, 'co...  
2  {'neg': 0.04, 'neu': 0.692, 'pos': 0.268, 'com...  
3  {'neg': 0.09, 'neu': 0.615, 'pos': 0.295, 'com...  
4  {'neg': 0.0, 'neu': 0.746, 'pos': 0.254, 'comp...

In [114]:
df['compound'] = df['scores'].apply(lambda d:d['compound'])
df.head()

label                                             review  \
0   pos  Stuning even for the non-gamer: This sound tra...   
1   pos  The best soundtrack ever to anything.: I'm rea...   
2   pos  Amazing!: This soundtrack is my favorite music...   
3   pos  Excellent Soundtrack: I truly like this soundt...   
4   pos  Remember, Pull Your Jaw Off The Floor After He...   

                                              scores  compound  
0  {'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'co...    0.9454  
1  {'neg': 0.018, 'neu': 0.837, 'pos': 0.145, 'co...    0.8957  
2  {'neg': 0.04, 'neu': 0.692, 'pos': 0.268, 'com...    0.9858  
3  {'neg': 0.09, 'neu': 0.615, 'pos': 0.295, 'com...    0.9814  
4  {'neg': 0.0, 'neu': 0.746, 'pos': 0.254, 'comp...    0.9781

In [116]:
df['comp_score'] = df['compound'].apply(lambda score: 'pos' if score >= 0 else 'neg')
df.head()

label                                             review  \
0   pos  Stuning even for the non-gamer: This sound tra...   
1   pos  The best soundtrack ever to anything.: I'm rea...   
2   pos  Amazing!: This soundtrack is my favorite music...   
3   pos  Excellent Soundtrack: I truly like this soundt...   
4   pos  Remember, Pull Your Jaw Off The Floor After He...   

                                              scores  compound comp_score  
0  {'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'co...    0.9454        pos  
1  {'neg': 0.018, 'neu': 0.837, 'pos': 0.145, 'co...    0.8957        pos  
2  {'neg': 0.04, 'neu': 0.692, 'pos': 0.268, 'com...    0.9858        pos  
3  {'neg': 0.09, 'neu': 0.615, 'pos': 0.295, 'com...    0.9814        pos  
4  {'neg': 0.0, 'neu': 0.746, 'pos': 0.254, 'comp...    0.9781        pos

#### Evaluation Metrics

In [119]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
accuracy_score(df['label'], df['comp_score'])

0.7098

In [123]:
#we have the correctly classified instance of positive and negative versus the incorrectly classified.
print(classification_report(df['label'], df['comp_score']))

              precision    recall  f1-score   support

         neg       0.86      0.52      0.64      5097
         pos       0.64      0.91      0.75      4903

    accuracy                           0.71     10000
   macro avg       0.75      0.71      0.70     10000
weighted avg       0.75      0.71      0.70     10000



In [125]:
#So you can see here, again it's not performing well with the negative for review
print(confusion_matrix(df['label'], df['comp_score']))

[[2630 2467]
 [ 435 4468]]


CONCLUSION:
Vader for the Amazon sentiment analysis is deffinitely not bad considering how
simple the process is, but it's also not excellent compared to maybe some state-of-the-art deep learning methods
for sentiment analysis.